

# CI Build Pipeline: Build and push image only, no deploy

steps:
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f', 'devops/Dockerfile',
        '-t', 'gcr.io/$PROJECT_ID/econome:$BUILD_ID',
        '-t', 'gcr.io/$PROJECT_ID/econome:latest',
        '.'
      ]

  - id: 'push-images'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push', 'gcr.io/$PROJECT_ID/econome:$BUILD_ID',
        '&&',
        'docker',
        'push', 'gcr.io/$PROJECT_ID/econome:latest'
      ]

images:
  - 'gcr.io/$PROJECT_ID/econome:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/econome:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '900s'